name: Demo_Hive_with_Bloc
description: Hive Implementation demo with bloc

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.2
  flutter_bloc: ^6.1.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  path_provider: ^1.6.28
  equatable: 1.1.1
  loading_overlay: ^0.2.1
  another_flushbar: ^1.10.11
  cached_network_image: ^2.5.0
  form_field_validator: ^1.0.1

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  build_runner: ^1.11.0

flutter:
  
  uses-material-design: true
